export interface CustomerData {
  _id: string,
  name: string,
  phone: string,
  sex: string,
  birthday: string,
  weixin: string,
  weixin_code_pic: string,
  country: string,
  city: string,
  address: string,
  zipcode: string,
  vip_card_date: string,
  vip_card_shop: string,
  vip_card_guide: string,
  vip_level: number,
  vip_exp: number,
  balance: number,
  recharge: number,
  recharge_reward: number,
  join_type: string,
}
